### ISSUE TITLE
BUG/ERROR ControlNet 1.1.232 issues & SD-CN

### ISSUE THREAD

**Issue by Duemellon** [volotat/SD-CN-Animation#181]
When I have SD-CN extension active ControlNet won't work for anything. Even in normal non SD-CD t2t, i2i, etc. The ControlNet subwindow opens, you put in the reference image, but the options to select which Control Type aren't working properly & the effects of the ControlNet type, regardless if it's Canny, Depth, OpenPose, etc. doesn't apply. 

I have:
- Disabled all extensions (including Control Net) other than SD-CD-Anim & that worked by itself
- Disabled all extensions, except Control Net, & it worked fine for t2t, i2i, etc
- Completely del'd the ControlNet extension folder, reinstalled from A1111's extension tab, same problem when SD-CD is running
- Completely del'd & reinstalled SD-CD from extension in A1111, same problem with SD-CD & running

I'm using Chrome. All pop-up, Flash blockers, etc. disabled. I tried in an icognito frame.

STRANGE PART
I used a vid clip in CD tab with Controlnet OpenPose to generate prior to this issue. IDK if I then had an update/upgrade run for CD-Anim or ControlNet afterwards as I went to extensions told it to check for update & ran (I usually don't check what all is changing).

**Comment by chuckkay** [comment]
i concur, it is caused by this extention or one of it's components

**Comment by Duemellon** [comment]
Any news? the SD-CN is the only one that allows ControlNet usage. AnimateDiff doesn't & Modelscope doesn't. I know there hasn't been an update in 2 months. I do hope this wasn't abandoned & the update can be just a small change.

**Comment by Pkhtjim** [comment]
Hopefully the issue is just something with Controlnet updating. I just got this and it sealed my ability to use controlnet on everything else until deleting this extension. Would love to try this out soon.

**Comment by nababuddin** [comment]
it appears that the issue might be related to the interaction between the ControlNet extension and the SD-CD extension. Here are a few steps you can try to troubleshoot the problem:

Clear Browser Cache: Sometimes, cached data can cause issues. Clear your browser's cache and cookies, then restart the browser.

Disable Extensions: Disable all extensions except for the ones necessary for ControlNet and SD-CD. This might help identify if there's a conflict between certain extensions.

Check for Updates: Ensure that both the ControlNet extension and SD-CD extension are up to date. If you're unsure about any updates that may have been applied, try to find release notes or update logs for the extensions to see if any changes might be affecting their compatibility.

Different Browser: If the issue persists in Chrome, try using a different browser like Firefox or Edge to see if the problem occurs there as well. This can help determine if the issue is browser-specific.

Incognito/Private Mode: You mentioned that you tried using Chrome's incognito mode, but it's worth noting that some extensions might still be active in incognito mode. Try using a different browser's private browsing mode to see if the problem persists there.

Extension Interaction: It's possible that there's an interaction between the ControlNet extension and the SD-CD extension that is causing the issue. Consider reaching out to the developers of these extensions or checking any documentation they provide for guidance on potential conflicts.

Reinstallation: If none of the above steps work, you might need to reinstall both the ControlNet extension and the SD-CD extension. However, before doing so, make sure to back up any important data or settings related to these extensions.

**Comment by Duemellon** [comment]
THANK YOU!! it works again. There are some other errors in the process but it doesn't bomb the entire A1111 anymore. Thanks!
