### ISSUE TITLE
LoRA compatibility

### ISSUE THREAD

**Issue by alexfredo** [volotat/SD-CN-Animation#3]
Is there a way to make LoRA works with your script ? I have enter the name of my lora file in the prompt but it doesn't works, thanks

**Comment by volotat** [comment]
Everything that works in Automatic1111/web-ui should work with the script also. The main reason to use web-ui API instead of Diffusers pipeline, for example, is to keep all features that web-ui brings. If there is something that does not work with a script that works in web-ui the most likely reason is a wrong API call format or the issue in the API itself.

**Comment by alexfredo** [comment]
You have right the problem was my settings I got LoRA working after change the denoising and the hed weight in the script.py
