### ISSUE TITLE
txt2video generation failure

### ISSUE THREAD

**Issue by borick** [volotat/SD-CN-Animation#42]
when i try to do txt2video it only generates 1 frame then stops

**Comment by maciekpoplawski** [comment]
same here. Nothing happening in console :( 
![image](https://github.com/volotat/SD-CN-Animation/assets/54249329/57ad62bd-13ec-47b9-8c2b-4792b7c2b630)

**Comment by volotat** [comment]
There is some error happening but a part of the code that handles the exception does not print it. My bad. This will be fixed in the next update. Regarding the problem itself I'm pretty sure that it is the same as described here: https://github.com/volotat/SD-CN-Animation/issues/33#issuecomment-1537991750

**Comment by maciekpoplawski** [comment]
Just to be sure. I checked default resolution of 768 x 512 and still nothing. Btw vid2vid works ok. Is it for sure the same error? Thx for reply.

**Comment by maciekpoplawski** [comment]
UPDATE from me: checked out on clean auto1111 install and text2video works. Probably some crash with other 283424 extensions i have on old auto1111 instance.
